# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171001_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
