"""
Django settings for soulsugar project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys
import urlparse
import dj_database_url
import boto
from boto.s3.key import Key
import boto.s3.connection

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2^7bum483b%^a!(r^$=ktp226q4*fa9v^*ylp)zi37hg8w*5-u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # custom apps
    'frontend',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'soulsugar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'soulsugar.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
urlparse.uses_netloc.append('mysql')
try:

    # Check to make sure DATABASES is set in settings.py file.
    # If not default to {}s

    if 'DATABASES' not in locals():
        DATABASES = {}

    if 'mysql://bb603e1a8c073f:06d45cbc@us-cdbr-iron-east-05.cleardb.net/heroku_16d6f79a11d7969' in os.environ:
        url = urlparse.urlparse(os.environ['mysql://bb603e1a8c073f:06d45cbc@us-cdbr-iron-east-05.cleardb.net/heroku_16d6f79a11d7969'])

        # Ensure default database exists.
        DATABASES['default'] = DATABASES.get('default', {})

        # Update with environment configuration.
        DATABASES['default'].update({
            'NAME': 'heroku_16d6f79a11d7969',
            'USER': 'bb603e1a8c073f',
            'PASSWORD': '06d45cbc',
            'HOST': 'us-cdbr-iron-east-05.cleardb.net',
            'PORT': '3306',
        })
        if self.connection.open:
            self.connection.stat()

        try:
            self.connection = MySQLdb.connect(host='us-cdbr-iron-east-05.cleardb.net',port='3306',db='heroku_16d6f79a11d7969',user='bb603e1a8c073f',passwd='06d45cbc')
        except MySQLdb.OperationalError, e:
            self.connection = None


        if url.scheme == 'mysql':
            DATABASES['default']['ENGINE'] = 'django.db.backends.mysql'
except Exception:
    print 'Unexpected error:', sys.exc_info()

DATABASES['default'] = dj_database_url.config(default='mysql://soulsugar_user:soulsugar@127.0.0.1:3306/soulsugar_db')
DATABASES['default']['OPTIONS'] = {
    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, "static_src", "static_root")

# MEDIA_URL = '/media/'

# MEDIA_ROOT = os.path.join(BASE_DIR, "static_src", "media_root")

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static_src", "our_static"),
    )

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

AWS_S3_HOST = 's3.ap-south-1.amazonaws.com'

AWS_ACCESS_KEY_ID = 'AKIAIXS2XR4IMMUZCHSQ'

AWS_SECRET_ACCESS_KEY = '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'

AWS_STORAGE_BUCKET_NAME = 'sss3bucket'

S3_URL = 'https://%s.s3.amazonaws.com' %AWS_STORAGE_BUCKET_NAME

STATIC_DIRECTORY = '/static/'

MEDIA_DIRECTORY = '/media/'

STATIC_URL = S3_URL + STATIC_DIRECTORY

MEDIA_URL = S3_URL + MEDIA_DIRECTORY

ADMIN_MEDIA_PREFIX = S3_URL + STATIC_DIRECTORY + 'admin/'

AWS_QUERYSTRING_AUTH = False